# Generated by Django 5.0 on 2024-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_done_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='test_mark',
            field=models.IntegerField(null=True),
        ),
    ]
