# Generated by Django 5.0 on 2024-03-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_useraccount_is_done_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
