# Generated by Django 5.0 on 2024-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_useraccount_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='unique_code',
            field=models.CharField(max_length=21, null=True, unique=True),
        ),
    ]
